import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto("http://localhost:3100/projects");
await page.waitForTimeout(700);
await page.getByRole("button", { name: "Nieuw project" }).click();
await page.waitForTimeout(300);
await page.locator("#np-customer").selectOption({ index: 1 });
await page.locator("#np-name").fill("Zone layout");
await page.getByRole("button", { name: "Project aanmaken" }).click();
await page.waitForTimeout(900);
await page.getByRole("button", { name: "Taak aanmaken" }).click();
await page.waitForTimeout(400);
await page.getByPlaceholder("Techniekruimte").first().fill("Techniekruimte 1");
await page.getByPlaceholder("Techniekruimte").first().blur();
await page.waitForTimeout(400);
console.log("'Taak' label:", await page.getByText("Taak", { exact: true }).count());
console.log("'Status' label:", await page.getByText("Status", { exact: true }).count());
console.log("badge 'Nog te doen':", await page.getByText("Nog te doen").count());
await page.locator("section, main").first().screenshot({ path: "demo-recordings/screenshots/zone.png" }).catch(async()=>{ await page.screenshot({ path: "demo-recordings/screenshots/zone.png" }); });
await browser.close();
console.log("done");
