import { chromium } from "playwright";
const KEY = "opero-state-leeg-v1";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto("http://localhost:3100/projects");
await page.waitForTimeout(700);
await page.getByRole("button", { name: "Nieuw project" }).click();
await page.waitForTimeout(300);
await page.locator("#np-customer").selectOption({ index: 1 });
await page.locator("#np-name").fill("Cmp");
await page.getByRole("button", { name: "Project aanmaken" }).click();
await page.waitForTimeout(900);
const projPath = new URL(page.url()).pathname;
const projId = projPath.split("/projects/")[1];
await page.getByRole("button", { name: "Taak aanmaken" }).click();
await page.waitForTimeout(400);
// add a regel
await page.getByRole("button", { name: "Taak toevoegen" }).first().click();
await page.waitForTimeout(250);
await page.locator("#tk-article").selectOption({ index: 1 });
await page.locator("#tk-qty").fill("1");
await page.locator("#tk-dia").fill("24");
await page.getByRole("button", { name: "Taak toevoegen" }).last().click();
await page.waitForTimeout(400);
await page.evaluate(({key,pid})=>{const d=JSON.parse(localStorage.getItem(key));const p=d.state.projects.find(x=>x.id===pid);if(p){p.installerIds=["tm-003"];p.meerwerk=[{id:"a",description:"1 m2 Bodemisolatie",amount:22,photos:[],createdAt:"2026-06-07",done:false,approvedByOffice:true,approvedByClient:true,rejected:false}];}d.state.activeProfileId="profile-monteur";localStorage.setItem(key,JSON.stringify(d));},{key:KEY,pid:projId});
await page.goto("http://localhost:3100"+projPath);
await page.waitForTimeout(800);
await page.locator(".min-w-0").first().screenshot({ path: "demo-recordings/screenshots/cmp.png" }).catch(async()=>{await page.screenshot({path:"demo-recordings/screenshots/cmp.png"});});
await browser.close();
console.log("done");
